baseURL = 'https://hhko.github.io/'
languageCode = 'ko-KR'
title = '배움은 설렘이다'
theme = ["docsy"]

## Language settings
#contentDir = "content/ko"
#defaultContentLanguage = "ko"
#defaultContentLanguageInSubdir = false
#enableRobotsTXT = true
#disableBrowserError = true

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/hhko/hhko.github.io"