baseURL = 'https://hhko.github.io/'
languageCode = 'ko-KR'
#title = '배움은 설렘이다'
theme = ["docsy"]

#
# Language settings
#

contentDir = "content/ko"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
disableBrowserError = true

#
# Language definitions.
#

[languages]
[languages.ko]
title = '배움은 설렘이다'
description = "More fun with you"
languageName = "한국어"
weight = 3
contentDir = "content/ko"
languagedirection = "ltr"

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/hhko/hhko.github.io"

#
# HTML + Markdown 표시
# 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

#
# UI 설정
#

[params.ui]
   # https://www.docsy.dev/docs/adding-content/navigation/#section-menu-options
   # Enable to show the side bar menu in its compact state.
   # 메뉴 1수준만 표시 유/무
   sidebar_menu_compact = true
   # Show expand/collapse icon for sidebar sections
   # 메뉴 expand/collapse 아이콘 표시 유/무
   #sidebar_menu_foldable = true

   # Enable the logo
   #navbar_logo = false
   # Enable the search box in the side bar.
   #sidebar_search_disable = false
   # Set to true to disable breadcrumb navigation.
   #breadcrumb_disable = false
   
   # Disable about button in footer
   #footer_about_disable = true